In [14]:
import numpy as np

def mulInverse(a,b):
    ri = [b,a]
    qi = [0,0]
    xi = [1,0]
    yi = [0,1]
    i = 2
    while True:
        ri.append(ri[i-2]%ri[i-1])
        qi.append(ri[i-2]//ri[i-1])
        xi.append(xi[i-2] - qi[i]*xi[i-1])
        yi.append(yi[i-2] - qi[i]*yi[i-1])

        if ri[i] == 1:
            break
        i += 1
    XI = (b+xi[-1]) if (xi[-1]<0) else (xi[-1])
    YI = (b+yi[-1]) if (yi[-1]<0) else (yi[-1])
    return YI

# PT = np.array([0,2,19])
PT = np.array([[15,0,24],[12,14,17],[4,12,14],[13,4,24]])
# Key = np.array([[0,11,15],[7,0,1],[4,19,0]])
Key = np.array([[17,17,5],[21,18,21],[2,2,19]])
CT = np.dot(PT,Key) % 26


### we need to find Key Inverse so Key Inverse = inverse of det(key) * adj(k)

# finding determinant of Key
detOfKey = round(np.linalg.det(Key) % 26) if np.linalg.det(Key) < 0 or np.linalg.det(Key)>26  else round(np.linalg.det(Key))
print(detOfKey)

# Finding det of Key Inverse
detOfKeyInverse = mulInverse(detOfKey, 26)
print(detOfKeyInverse)

# Now Finding Adjoint of Key 
adjKey = np.linalg.det(Key) * np.linalg.inv(Key)
adjKey = adjKey.round() % 26

# Now finally Key Inverse = detKeyInverse * adjKey
keyInverse = (detOfKeyInverse * adjKey) % 26
# print(keyInverse)

### Finally multiply Cipher Text with Key Inverse Matrix
DT = np.dot(CT, keyInverse) % 26
DT=DT.astype(int)
print(DT)


23
17
[[15  0 24]
 [12 14 17]
 [ 4 12 14]
 [13  4 24]]


In [15]:
a="Hii in amm "
a.replace(" ","")

'Hiiinamm'